-- MySQL Script generated by MySQL Workbench
-- 2015年06月30日 星期二 16时03分05秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL COMMENT '姓名',
  `gender` VARCHAR(45) NULL COMMENT '性别',
  `nation` VARCHAR(45) NULL COMMENT '民族',
  `birthday` VARCHAR(45) NULL COMMENT '出生日期',
  `politics` VARCHAR(45) NULL COMMENT '政治面貌',
  `diplomano` VARCHAR(45) NULL COMMENT '毕业证号',
  `college` VARCHAR(45) NULL COMMENT '院系',
  `class` VARCHAR(45) NULL COMMENT '班级',
  `major` VARCHAR(45) NULL COMMENT '专业',
  `studentNo` VARCHAR(45) NULL COMMENT '学号',
  `address` VARCHAR(45) NULL COMMENT '生源所在地',
  `img` VARCHAR(45) NULL COMMENT '学生照片',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '学生信息表';


-- -----------------------------------------------------
-- Table `mydb`.`college`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`college` (
  `id` INT NOT NULL COMMENT '学院id',
  `name` VARCHAR(45) NULL COMMENT '学院名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '学院表\n';


-- -----------------------------------------------------
-- Table `mydb`.`major`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`major` (
  `id` INT NOT NULL COMMENT '专业id',
  `name` VARCHAR(45) NULL COMMENT '名称',
  `college_id` INT NOT NULL COMMENT '学院id',
  PRIMARY KEY (`id`),
  INDEX `fk_major_collage_idx` (`college_id` ASC),
  CONSTRAINT `fk_major_college`
    FOREIGN KEY (`college_id`)
    REFERENCES `mydb`.`college` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '专业表';


-- -----------------------------------------------------
-- Table `mydb`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`class` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL COMMENT '班级名',
  `major_id` INT NOT NULL COMMENT '专业id',
  PRIMARY KEY (`id`),
  INDEX `fk_class_major1_idx` (`major_id` ASC),
  CONSTRAINT `fk_class_major1`
    FOREIGN KEY (`major_id`)
    REFERENCES `mydb`.`major` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '班级表';


-- -----------------------------------------------------
-- Table `mydb`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`material` (
  `id` INT NOT NULL COMMENT '材料id',
  `type` VARCHAR(45) NULL COMMENT '类型',
  `name` VARCHAR(45) NULL COMMENT '名称',
  `remark` VARCHAR(45) NULL COMMENT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '材料信息表';


-- -----------------------------------------------------
-- Table `mydb`.`archives`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`archives` (
  `id` VARCHAR(45) NULL COMMENT 'id',
  `student_id` INT NOT NULL COMMENT '学生id',
  `archiveNo` VARCHAR(45) NULL COMMENT '档案号',
  `jiYaoNo` VARCHAR(45) NULL COMMENT '机要号',
  `isSend` VARCHAR(45) NULL COMMENT '是否已调',
  `sendWay` VARCHAR(45) NULL COMMENT '调档方式',
  `isDuyan` VARCHAR(45) NULL COMMENT '是否读研',
  `firstSend` VARCHAR(45) NULL COMMENT '一次调档',
  `secondSend` VARCHAR(45) NULL COMMENT '二次调档',
  `sendAddress` VARCHAR(45) NULL COMMENT '档案去向',
  `hMaterial` VARCHAR(45) NULL COMMENT '高中材料\n',
  `uMaterial` VARCHAR(45) NULL COMMENT '本科材料',
  `mMaterial` VARCHAR(45) NULL COMMENT '硕士材料',
  `dMaterial` VARCHAR(45) NULL COMMENT '博士材料',
  `pMaterial` VARCHAR(45) NULL COMMENT '党员材料',
  `oMaterial` VARCHAR(45) NULL COMMENT '其他材料\n',
  `zMaterial` VARCHAR(45) NULL COMMENT '专升本材料',
  `reMark` VARCHAR(45) NULL COMMENT '备注\n',
  INDEX `fk_archives_student1_idx` (`student_id` ASC),
  CONSTRAINT `fk_archives_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '学生档案信息';


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `email` VARCHAR(45) NULL COMMENT '邮箱',
  `name` VARCHAR(45) NULL COMMENT '姓名',
  `phone` VARCHAR(45) NULL COMMENT '手机',
  `pwd` VARCHAR(45) NULL COMMENT '密码',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '管理员表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;